### ISSUE TITLE
Cannot use `sshsrv username@example.com`

### ISSUE THREAD

**Issue by UlyssesZh** [Crosse/sshsrv#4]
If I use `sshsrv username@example.com`, the wrapper will not look up for SRV records and behaves identically as `ssh username@example.com`. I have to use `sshsrv example.com -l username` instead to make it look up for SRV records.
It seems that this project has not been maintained for a long time, but this is a rather low-hanging fruit, so I hope someone may fix this.

**Comment by Crosse** [comment]
This is what I get when I use the `user@host` format:
```
$ ./sshsrv -v seth@my.host.org
Found 1 SRV record(s) for _ssh._tcp.my.host.org.
Record 0:       0 0 2022 my.host.org.
Target for my.host.org is my.host.org:2022
command: /opt/pkg/bin/ssh -p 2022 -v -l seth my.host.org
[…]
```

Would you mind running the command with `-v` and providing that output? Redactions are fine, and I only need to see what I have above.

Thanks for the report!

**Comment by UlyssesZh** [comment]
> This is what I get when I use the `user@host` format:
> ```
> $ ./sshsrv -v seth@my.host.org
> Found 1 SRV record(s) for _ssh._tcp.my.host.org.
> Record 0:       0 0 22 my.host.org.
> Target for my.host.org is my.host.org:22
> command: /opt/pkg/bin/ssh -p 22 -v -l seth my.host.org
> […]
> ```
> 
> Would you mind running the command with `-v` and providing that output? Redactions are fine, and I only need to see what I have above.
> 
> Thanks for the report!

Oh, the SRV lookup is good. What I have found is actually another bug: with `sshsrv user@example.com`, the username is read as <code>&nbsp;user</code> instead of `user` (with an extra space in front).

**Comment by Crosse** [comment]
Ah, I see. It should be fixed now. Let me know if it works for you!

**Comment by Crosse** [comment]
I also added releases, so you can download a pre-built binary now. Feel free to reopen this if your issue isn't resolved. Thanks!
