### ISSUE TITLE
Semantic Version number

### ISSUE THREAD

**Issue by joshbode** [Crosse/sshsrv#7]
I use a tool called Mise to manage the installation of tools into my development environment and one of the tools I install is `sshsrv`.

To identify the available versions of `go`-based tools, Mise executes the following command internally:
```
$ go list -m -versions -json github.com/Crosse/sshsrv
{
        "Path": "github.com/Crosse/sshsrv"
}
```
Usually there would be a `Versions` key in the response, however for `sshsrv` there isn't any (see https://github.com/jdx/mise/issues/3597).

I believe that `go list` requires full semantic versions (e.g. `vX.Y.Z`) to include a specific version in the `go list -m -versions` response, however the only version tagged in the `sshsrv` repo is `v1.0` (rather than `v1.0.0`).

Would it be possible to include a tag for `v1.0.0`, please?

**Comment by Crosse** [comment]
I've pushed a new tag:

```
$ go list -m -versions -json github.com/Crosse/sshsrv
{
        "Path": "github.com/Crosse/sshsrv",
        "Versions": [
                "v1.0.1"
        ],
        "Main": true,
        "Dir": "/Users/seth/code/mine/sshsrv",
        "GoMod": "/Users/seth/code/mine/sshsrv/go.mod",
        "GoVersion": "1.23.0"
}
```

(No code change; I probably should have tagged it as v1.0.0, but oh well.) Hopefully this will fix your immediate issue? Let me know if it doesn't.

I honestly didn't realize people used this all that much. I've got some updates I need to make, so maybe there will be a v1.1.0 soon…

**Comment by joshbode** [comment]
Awesome! Thank you.

I've been using sshsrv in conjunction with pktriot (as an alternative to ngrok), since it provides a stable (but initially randomly allocated) port number for tunnels (unlike ngrok which is random each time unless you pay). I got sick of remembering which port was allocated where, but using the SRV record is an elegant way to expose the allocated port :)
